server:
  port: 8086
  servlet:
    context-path: /store/api
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5433/store
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10
token:
    secret: ${TOKEN_SECRET}
    expiration-in-seconds:  1000
cache:
  ttl: #in secods
      CUSTOMER_LIST_DTO_CACHE: 30
      ORDER_DTO_CACHE: 30
      ORDER_LIST_DTO_CACHE: 30
      CUSTOMER_DTO_CACHE: 30
      CUSTOMER_SEARCH_LIST_DTO_CACHE: 30
      PRODUCT_LIST_DTO_CACHE: 30
      PRODUCT_DTO_CACHE: 30
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml