spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/store
    username: admin
    password: admin
  data:
    redis:
      time-to-live: 60000
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10
cache:
  ttl: #in secods
      CUSTOMER_LIST_DTO_CACHE: 30
      ORDER_DTO_CACHE: 30
      ORDER_LIST_DTO_CACHE: 30
      CUSTOMER_DTO_CACHE: 30
      CUSTOMER_SEARCH_LIST_DTO_CACHE: 30
      PRODUCT_LIST_DTO_CACHE: 30
      PRODUCT_DTO_CACHE: 30
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml