name: CI/CD Pipeline

on:
  push:
    branches:
        - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/store

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew.bat

      - name: Run Unit Tests
        run: gradlew.bat test

      - name: Run Integration Tests
        run: gradlew.bat integrationTest

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push $IMAGE_NAME
