services:
  store:
    container_name: store
    image: mumakahdo/store
    restart: always
    environment:
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - TOKEN_SECRET=IS5IobIItq0pRX9JL9TvdQ40Oa93u2Wojlign4V3L30
    ports:
      - "8086:8086"
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=store
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    image: postgres:16.2
    command: postgres -c wal_level=logical
  redis:
    image: redis
    container_name: redis-local
    ports:
      - "6379:6379"
volumes:
  postgres:
    external: false
    name: postgres

networks: {}
